### PR TITLE
Fix browser tests by importing the shared tests instead of exporting

### LINKED ISSUE #195: CI is currently failing due to breaking change in dart's test package
https://pub.dev/packages/test/changelog#1290

It seems like we're not allowed to `export <file_with_main>` anymore and we have to declare `main()` directly on the actual test 😬 

Otherwise this causes:

```
To run this test again: dart test test/jspm_test.dart -p vm --plain-name 'loading test/jspm_test.dart'
00:00 +0 -7: loading test/webpack_import_test.dart [E]                                                                                                                                                                                                                                                                        
  Failed to load "test/webpack_import_test.dart": Missing definition of `main` method.
```

Test from CI runs with:
```
dart run grinder before-test
dart run test --platform chrome --exclude-tags not-on-gh-actions
```

### PR DESCRIPTION
**Pull request by Goodwine**
Previously we called 'export' to append main() into the test file. Dart Test package 1.29.0 now disallows this pattern. TIL that the test package is released separate from the main Dart binary!

Fixes #195

### CODE REVIEW

File: browser_library_test/test/esbuild_require_test.dart [hunk 1]
```diff
@@ -17,4 +17,8 @@ library;
 
 import 'package:test/test.dart';
 
-export 'browser_test_shared.dart';
+import 'browser_test_shared.dart' as shared_browser_tests;
+
+void main() {
+  shared_browser_tests.main();
+}
```
Comment (Goodwine) [inline browser_library_test/test/esbuild_require_test.dart:24]: As I haven't been working with Dart, I'm not sure if this is better over `void main() => shared_browser_tests.main()` 🤔 

I kinda like it better like this instead of an arrow function, but maybe that's my Go-brain talking lol

**Review by nex3 — APPROVED** [review]
